[package]
name = "ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# FIXME: Should we use a workspace for this?

[dependencies]
symbol = { path = "../symbol" }
location = { path = "../location" }
