[package]
name = "error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
location = { path = "../location" }
xparser = { path = "../xparser" }
colored = "2.0"
